<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'path' => 'flags/af.svg'],
            ['name' => 'Albania', 'path' => 'flags/al.svg'],
            ['name' => 'Algeria', 'path' => 'flags/dz.svg'],
            ['name' => 'Andorra', 'path' => 'flags/ad.svg'],
            ['name' => 'Angola', 'path' => 'flags/ao.svg'],
            ['name' => 'Antigua and Barbuda', 'path' => 'flags/ag.svg'],
            ['name' => 'Argentina', 'path' => 'flags/ar.svg'],
            ['name' => 'Armenia', 'path' => 'flags/am.svg'],
            ['name' => 'Australia', 'path' => 'flags/au.svg'],
            ['name' => 'Austria', 'path' => 'flags/at.svg'],
            ['name' => 'Azerbaijan', 'path' => 'flags/az.svg'],
            ['name' => 'Bahamas', 'path' => 'flags/bs.svg'],
            ['name' => 'Bahrain', 'path' => 'flags/bh.svg'],
            ['name' => 'Bangladesh', 'path' => 'flags/bd.svg'],
            ['name' => 'Barbados', 'path' => 'flags/bb.svg'],
            ['name' => 'Belarus', 'path' => 'flags/by.svg'],
            ['name' => 'Belgium', 'path' => 'flags/be.svg'],
            ['name' => 'Belize', 'path' => 'flags/bz.svg'],
            ['name' => 'Benin', 'path' => 'flags/bj.svg'],
            ['name' => 'Bhutan', 'path' => 'flags/bt.svg'],
            ['name' => 'Bolivia', 'path' => 'flags/bo.svg'],
            ['name' => 'Bosnia and Herzegovina', 'path' => 'flags/ba.svg'],
            ['name' => 'Botswana', 'path' => 'flags/bw.svg'],
            ['name' => 'Brazil', 'path' => 'flags/br.svg'],
            ['name' => 'Brunei', 'path' => 'flags/bn.svg'],
            ['name' => 'Bulgaria', 'path' => 'flags/bg.svg'],
            ['name' => 'Burkina Faso', 'path' => 'flags/bf.svg'],
            ['name' => 'Burundi', 'path' => 'flags/bi.svg'],
            ['name' => 'Cabo Verde', 'path' => 'flags/cv.svg'],
            ['name' => 'Cambodia', 'path' => 'flags/kh.svg'],
            ['name' => 'Cameroon', 'path' => 'flags/cm.svg'],
            ['name' => 'Canada', 'path' => 'flags/ca.svg'],
            ['name' => 'Central African Republic', 'path' => 'flags/cf.svg'],
            ['name' => 'Chad', 'path' => 'flags/td.svg'],
            ['name' => 'Chile', 'path' => 'flags/cl.svg'],
            ['name' => 'China', 'path' => 'flags/cn.svg'],
            ['name' => 'Colombia', 'path' => 'flags/co.svg'],
            ['name' => 'Comoros', 'path' => 'flags/km.svg'],
            ['name' => 'Congo, Democratic Republic of the', 'path' => 'flags/cd.svg'],
            ['name' => 'Congo, Republic of the', 'path' => 'flags/cg.svg'],
            ['name' => 'Costa Rica', 'path' => 'flags/cr.svg'],
            ['name' => 'Croatia', 'path' => 'flags/hr.svg'],
            ['name' => 'Cuba', 'path' => 'flags/cu.svg'],
            ['name' => 'Cyprus', 'path' => 'flags/cy.svg'],
            ['name' => 'Czech Republic', 'path' => 'flags/cz.svg'],
            ['name' => 'Denmark', 'path' => 'flags/dk.svg'],
            ['name' => 'Djibouti', 'path' => 'flags/dj.svg'],
            ['name' => 'Dominica', 'path' => 'flags/dm.svg'],
            ['name' => 'Dominican Republic', 'path' => 'flags/do.svg'],
            ['name' => 'Ecuador', 'path' => 'flags/ec.svg'],
            ['name' => 'Egypt', 'path' => 'flags/eg.svg'],
            ['name' => 'El Salvador', 'path' => 'flags/sv.svg'],
            ['name' => 'Equatorial Guinea', 'path' => 'flags/gq.svg'],
            ['name' => 'Eritrea', 'path' => 'flags/er.svg'],
            ['name' => 'Estonia', 'path' => 'flags/ee.svg'],
            ['name' => 'Eswatini', 'path' => 'flags/sz.svg'],
            ['name' => 'Ethiopia', 'path' => 'flags/et.svg'],
            ['name' => 'Fiji', 'path' => 'flags/fj.svg'],
            ['name' => 'Finland', 'path' => 'flags/fi.svg'],
            ['name' => 'France', 'path' => 'flags/fr.svg'],
            ['name' => 'Gabon', 'path' => 'flags/ga.svg'],
            ['name' => 'Gambia', 'path' => 'flags/gm.svg'],
            ['name' => 'Georgia', 'path' => 'flags/ge.svg'],
            ['name' => 'Germany', 'path' => 'flags/de.svg'],
            ['name' => 'Ghana', 'path' => 'flags/gh.svg'],
            ['name' => 'Greece', 'path' => 'flags/gr.svg'],
            ['name' => 'Grenada', 'path' => 'flags/gd.svg'],
            ['name' => 'Guatemala', 'path' => 'flags/gt.svg'],
            ['name' => 'Guinea', 'path' => 'flags/gn.svg'],
            ['name' => 'Guinea-Bissau', 'path' => 'flags/gw.svg'],
            ['name' => 'Guyana', 'path' => 'flags/gy.svg'],
            ['name' => 'Haiti', 'path' => 'flags/ht.svg'],
            ['name' => 'Honduras', 'path' => 'flags/hn.svg'],
            ['name' => 'Hungary', 'path' => 'flags/hu.svg'],
            ['name' => 'Iceland', 'path' => 'flags/is.svg'],
            ['name' => 'India', 'path' => 'flags/in.svg'],
            ['name' => 'Indonesia', 'path' => 'flags/id.svg'],
            ['name' => 'Iran', 'path' => 'flags/ir.svg'],
            ['name' => 'Iraq', 'path' => 'flags/iq.svg'],
            ['name' => 'Ireland', 'path' => 'flags/ie.svg'],
            ['name' => 'Israel', 'path' => 'flags/il.svg'],
            ['name' => 'Italy', 'path' => 'flags/it.svg'],
            ['name' => 'Jamaica', 'path' => 'flags/jm.svg'],
            ['name' => 'Japan', 'path' => 'flags/jp.svg'],
            ['name' => 'Jordan', 'path' => 'flags/jo.svg'],
            ['name' => 'Kazakhstan', 'path' => 'flags/kz.svg'],
            ['name' => 'Kenya', 'path' => 'flags/ke.svg'],
            ['name' => 'Kiribati', 'path' => 'flags/ki.svg'],
            ['name' => 'Korea, North', 'path' => 'flags/kp.svg'],
            ['name' => 'Korea, South', 'path' => 'flags/kr.svg'],
            ['name' => 'Kuwait', 'path' => 'flags/kw.svg'],
            ['name' => 'Kyrgyzstan', 'path' => 'flags/kg.svg'],
            ['name' => 'Laos', 'path' => 'flags/la.svg'],
            ['name' => 'Latvia', 'path' => 'flags/lv.svg'],
            ['name' => 'Lebanon', 'path' => 'flags/lb.svg'],
            ['name' => 'Lesotho', 'path' => 'flags/ls.svg'],
            ['name' => 'Liberia', 'path' => 'flags/lr.svg'],
            ['name' => 'Libya', 'path' => 'flags/ly.svg'],
            ['name' => 'Liechtenstein', 'path' => 'flags/li.svg'],
            ['name' => 'Lithuania', 'path' => 'flags/lt.svg'],
            ['name' => 'Luxembourg', 'path' => 'flags/lu.svg'],
            ['name' => 'Madagascar', 'path' => 'flags/mg.svg'],
            ['name' => 'Malawi', 'path' => 'flags/mw.svg'],
            ['name' => 'Malaysia', 'path' => 'flags/my.svg'],
            ['name' => 'Maldives', 'path' => 'flags/mv.svg'],
            ['name' => 'Mali', 'path' => 'flags/ml.svg'],
            ['name' => 'Malta', 'path' => 'flags/mt.svg'],
            ['name' => 'Marshall Islands', 'path' => 'flags/mh.svg'],
            ['name' => 'Mauritania', 'path' => 'flags/mr.svg'],
            ['name' => 'Mauritius', 'path' => 'flags/mu.svg'],
            ['name' => 'Mexico', 'path' => 'flags/mx.svg'],
            ['name' => 'Micronesia', 'path' => 'flags/fm.svg'],
            ['name' => 'Moldova', 'path' => 'flags/md.svg'],
            ['name' => 'Monaco', 'path' => 'flags/mc.svg'],
            ['name' => 'Mongolia', 'path' => 'flags/mn.svg'],
            ['name' => 'Montenegro', 'path' => 'flags/me.svg'],
            ['name' => 'Morocco', 'path' => 'flags/ma.svg'],
            ['name' => 'Mozambique', 'path' => 'flags/mz.svg'],
            ['name' => 'Myanmar', 'path' => 'flags/mm.svg'],
            ['name' => 'Namibia', 'path' => 'flags/na.svg'],
            ['name' => 'Nauru', 'path' => 'flags/nr.svg'],
            ['name' => 'Nepal', 'path' => 'flags/np.svg'],
            ['name' => 'Netherlands', 'path' => 'flags/nl.svg'],
            ['name' => 'New Zealand', 'path' => 'flags/nz.svg'],
            ['name' => 'Nicaragua', 'path' => 'flags/ni.svg'],
            ['name' => 'Niger', 'path' => 'flags/ne.svg'],
            ['name' => 'Nigeria', 'path' => 'flags/ng.svg'],
            ['name' => 'North Macedonia', 'path' => 'flags/mk.svg'],
            ['name' => 'Norway', 'path' => 'flags/no.svg'],
            ['name' => 'Oman', 'path' => 'flags/om.svg'],
            ['name' => 'Pakistan', 'path' => 'flags/pk.svg'],
            ['name' => 'Palau', 'path' => 'flags/pw.svg'],
            ['name' => 'Palestine', 'path' => 'flags/ps.svg'],
            ['name' => 'Panama', 'path' => 'flags/pa.svg'],
            ['name' => 'Papua New Guinea', 'path' => 'flags/pg.svg'],
            ['name' => 'Paraguay', 'path' => 'flags/py.svg'],
            ['name' => 'Peru', 'path' => 'flags/pe.svg'],
            ['name' => 'Philippines', 'path' => 'flags/ph.svg'],
            ['name' => 'Poland', 'path' => 'flags/pl.svg'],
            ['name' => 'Portugal', 'path' => 'flags/pt.svg'],
            ['name' => 'Qatar', 'path' => 'flags/qa.svg'],
            ['name' => 'Romania', 'path' => 'flags/ro.svg'],
            ['name' => 'Russia', 'path' => 'flags/ru.svg'],
            ['name' => 'Rwanda', 'path' => 'flags/rw.svg'],
            ['name' => 'Saint Kitts and Nevis', 'path' => 'flags/kn.svg'],
            ['name' => 'Saint Lucia', 'path' => 'flags/lc.svg'],
            ['name' => 'Saint Vincent and the Grenadines', 'path' => 'flags/vc.svg'],
            ['name' => 'Samoa', 'path' => 'flags/ws.svg'],
            ['name' => 'San Marino', 'path' => 'flags/sm.svg'],
            ['name' => 'Sao Tome and Principe', 'path' => 'flags/st.svg'],
            ['name' => 'Saudi Arabia', 'path' => 'flags/sa.svg'],
            ['name' => 'Senegal', 'path' => 'flags/sn.svg'],
            ['name' => 'Serbia', 'path' => 'flags/rs.svg'],
            ['name' => 'Seychelles', 'path' => 'flags/sc.svg'],
            ['name' => 'Sierra Leone', 'path' => 'flags/sl.svg'],
            ['name' => 'Singapore', 'path' => 'flags/sg.svg'],
            ['name' => 'Slovakia', 'path' => 'flags/sk.svg'],
            ['name' => 'Slovenia', 'path' => 'flags/si.svg'],
            ['name' => 'Solomon Islands', 'path' => 'flags/sb.svg'],
            ['name' => 'Somalia', 'path' => 'flags/so.svg'],
            ['name' => 'South Africa', 'path' => 'flags/za.svg'],
            ['name' => 'South Sudan', 'path' => 'flags/ss.svg'],
            ['name' => 'Spain', 'path' => 'flags/es.svg'],
            ['name' => 'Sri Lanka', 'path' => 'flags/lk.svg'],
            ['name' => 'Sudan', 'path' => 'flags/sd.svg'],
            ['name' => 'Suriname', 'path' => 'flags/sr.svg'],
            ['name' => 'Sweden', 'path' => 'flags/se.svg'],
            ['name' => 'Switzerland', 'path' => 'flags/ch.svg'],
            ['name' => 'Syria', 'path' => 'flags/sy.svg'],
            ['name' => 'Taiwan', 'path' => 'flags/tw.svg'],
            ['name' => 'Tajikistan', 'path' => 'flags/tj.svg'],
            ['name' => 'Tanzania', 'path' => 'flags/tz.svg'],
            ['name' => 'Thailand', 'path' => 'flags/th.svg'],
            ['name' => 'Timor-Leste', 'path' => 'flags/tl.svg'],
            ['name' => 'Togo', 'path' => 'flags/tg.svg'],
            ['name' => 'Tonga', 'path' => 'flags/to.svg'],
            ['name' => 'Trinidad and Tobago', 'path' => 'flags/tt.svg'],
            ['name' => 'Tunisia', 'path' => 'flags/tn.svg'],
            ['name' => 'Turkey', 'path' => 'flags/tr.svg'],
            ['name' => 'Turkmenistan', 'path' => 'flags/tm.svg'],
            ['name' => 'Tuvalu', 'path' => 'flags/tv.svg'],
            ['name' => 'Uganda', 'path' => 'flags/ug.svg'],
            ['name' => 'Ukraine', 'path' => 'flags/ua.svg'],
            ['name' => 'United Arab Emirates', 'path' => 'flags/ae.svg'],
            ['name' => 'United Kingdom', 'path' => 'flags/gb.svg'],
            ['name' => 'United States', 'path' => 'flags/us.svg'],
            ['name' => 'Uruguay', 'path' => 'flags/uy.svg'],
            ['name' => 'Uzbekistan', 'path' => 'flags/uz.svg'],
            ['name' => 'Vanuatu', 'path' => 'flags/vu.svg'],
            ['name' => 'Vatican City', 'path' => 'flags/va.svg'],
            ['name' => 'Venezuela', 'path' => 'flags/ve.svg'],
            ['name' => 'Vietnam', 'path' => 'flags/vn.svg'],
            ['name' => 'Yemen', 'path' => 'flags/ye.svg'],
            ['name' => 'Zambia', 'path' => 'flags/zm.svg'],
            ['name' => 'Zimbabwe', 'path' => 'flags/zw.svg'],
        ];
        DB::table('countries')->insert($countries);
    }
}
