<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TerritoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $territories = [
            ['name' => 'Global', 'flag' => 'https://bugfunx.com/flags/globe.svg'],
            ['name' => 'Afghanistan', 'flag' => 'https://bugfunx.com/flags/af.svg'],
            ['name' => 'Albania', 'flag' => 'https://bugfunx.com/flags/al.svg'],
            ['name' => 'Algeria', 'flag' => 'https://bugfunx.com/flags/dz.svg'],
            ['name' => 'Andorra', 'flag' => 'https://bugfunx.com/flags/ad.svg'],
            ['name' => 'Angola', 'flag' => 'https://bugfunx.com/flags/ao.svg'],
            ['name' => 'Antigua and Barbuda', 'flag' => 'https://bugfunx.com/flags/ag.svg'],
            ['name' => 'Argentina', 'flag' => 'https://bugfunx.com/flags/ar.svg'],
            ['name' => 'Armenia', 'flag' => 'https://bugfunx.com/flags/am.svg'],
            ['name' => 'Australia', 'flag' => 'https://bugfunx.com/flags/au.svg'],
            ['name' => 'Austria', 'flag' => 'https://bugfunx.com/flags/at.svg'],
            ['name' => 'Azerbaijan', 'flag' => 'https://bugfunx.com/flags/az.svg'],
            ['name' => 'Bahamas', 'flag' => 'https://bugfunx.com/flags/bs.svg'],
            ['name' => 'Bahrain', 'flag' => 'https://bugfunx.com/flags/bh.svg'],
            ['name' => 'Bangladesh', 'flag' => 'https://bugfunx.com/flags/bd.svg'],
            ['name' => 'Barbados', 'flag' => 'https://bugfunx.com/flags/bb.svg'],
            ['name' => 'Belarus', 'flag' => 'https://bugfunx.com/flags/by.svg'],
            ['name' => 'Belgium', 'flag' => 'https://bugfunx.com/flags/be.svg'],
            ['name' => 'Belize', 'flag' => 'https://bugfunx.com/flags/bz.svg'],
            ['name' => 'Benin', 'flag' => 'https://bugfunx.com/flags/bj.svg'],
            ['name' => 'Bhutan', 'flag' => 'https://bugfunx.com/flags/bt.svg'],
            ['name' => 'Bolivia', 'flag' => 'https://bugfunx.com/flags/bo.svg'],
            ['name' => 'Bosnia and Herzegovina', 'flag' => 'https://bugfunx.com/flags/ba.svg'],
            ['name' => 'Botswana', 'flag' => 'https://bugfunx.com/flags/bw.svg'],
            ['name' => 'Brazil', 'flag' => 'https://bugfunx.com/flags/br.svg'],
            ['name' => 'Brunei', 'flag' => 'https://bugfunx.com/flags/bn.svg'],
            ['name' => 'Bulgaria', 'flag' => 'https://bugfunx.com/flags/bg.svg'],
            ['name' => 'Burkina Faso', 'flag' => 'https://bugfunx.com/flags/bf.svg'],
            ['name' => 'Burundi', 'flag' => 'https://bugfunx.com/flags/bi.svg'],
            ['name' => 'Cabo Verde', 'flag' => 'https://bugfunx.com/flags/cv.svg'],
            ['name' => 'Cambodia', 'flag' => 'https://bugfunx.com/flags/kh.svg'],
            ['name' => 'Cameroon', 'flag' => 'https://bugfunx.com/flags/cm.svg'],
            ['name' => 'Canada', 'flag' => 'https://bugfunx.com/flags/ca.svg'],
            ['name' => 'Central African Republic', 'flag' => 'https://bugfunx.com/flags/cf.svg'],
            ['name' => 'Chad', 'flag' => 'https://bugfunx.com/flags/td.svg'],
            ['name' => 'Chile', 'flag' => 'https://bugfunx.com/flags/cl.svg'],
            ['name' => 'China', 'flag' => 'https://bugfunx.com/flags/cn.svg'],
            ['name' => 'Colombia', 'flag' => 'https://bugfunx.com/flags/co.svg'],
            ['name' => 'Comoros', 'flag' => 'https://bugfunx.com/flags/km.svg'],
            ['name' => 'Congo, Democratic Republic of the', 'flag' => 'https://bugfunx.com/flags/cd.svg'],
            ['name' => 'Congo, Republic of the', 'flag' => 'https://bugfunx.com/flags/cg.svg'],
            ['name' => 'Costa Rica', 'flag' => 'https://bugfunx.com/flags/cr.svg'],
            ['name' => 'Croatia', 'flag' => 'https://bugfunx.com/flags/hr.svg'],
            ['name' => 'Cuba', 'flag' => 'https://bugfunx.com/flags/cu.svg'],
            ['name' => 'Cyprus', 'flag' => 'https://bugfunx.com/flags/cy.svg'],
            ['name' => 'Czech Republic', 'flag' => 'https://bugfunx.com/flags/cz.svg'],
            ['name' => 'Denmark', 'flag' => 'https://bugfunx.com/flags/dk.svg'],
            ['name' => 'Djibouti', 'flag' => 'https://bugfunx.com/flags/dj.svg'],
            ['name' => 'Dominica', 'flag' => 'https://bugfunx.com/flags/dm.svg'],
            ['name' => 'Dominican Republic', 'flag' => 'https://bugfunx.com/flags/do.svg'],
            ['name' => 'Ecuador', 'flag' => 'https://bugfunx.com/flags/ec.svg'],
            ['name' => 'Egypt', 'flag' => 'https://bugfunx.com/flags/eg.svg'],
            ['name' => 'El Salvador', 'flag' => 'https://bugfunx.com/flags/sv.svg'],
            ['name' => 'Equatorial Guinea', 'flag' => 'https://bugfunx.com/flags/gq.svg'],
            ['name' => 'Eritrea', 'flag' => 'https://bugfunx.com/flags/er.svg'],
            ['name' => 'Estonia', 'flag' => 'https://bugfunx.com/flags/ee.svg'],
            ['name' => 'Eswatini', 'flag' => 'https://bugfunx.com/flags/sz.svg'],
            ['name' => 'Ethiopia', 'flag' => 'https://bugfunx.com/flags/et.svg'],
            ['name' => 'Fiji', 'flag' => 'https://bugfunx.com/flags/fj.svg'],
            ['name' => 'Finland', 'flag' => 'https://bugfunx.com/flags/fi.svg'],
            ['name' => 'France', 'flag' => 'https://bugfunx.com/flags/fr.svg'],
            ['name' => 'Gabon', 'flag' => 'https://bugfunx.com/flags/ga.svg'],
            ['name' => 'Gambia', 'flag' => 'https://bugfunx.com/flags/gm.svg'],
            ['name' => 'Georgia', 'flag' => 'https://bugfunx.com/flags/ge.svg'],
            ['name' => 'Germany', 'flag' => 'https://bugfunx.com/flags/de.svg'],
            ['name' => 'Ghana', 'flag' => 'https://bugfunx.com/flags/gh.svg'],
            ['name' => 'Greece', 'flag' => 'https://bugfunx.com/flags/gr.svg'],
            ['name' => 'Grenada', 'flag' => 'https://bugfunx.com/flags/gd.svg'],
            ['name' => 'Guatemala', 'flag' => 'https://bugfunx.com/flags/gt.svg'],
            ['name' => 'Guinea', 'flag' => 'https://bugfunx.com/flags/gn.svg'],
            ['name' => 'Guinea-Bissau', 'flag' => 'https://bugfunx.com/flags/gw.svg'],
            ['name' => 'Guyana', 'flag' => 'https://bugfunx.com/flags/gy.svg'],
            ['name' => 'Haiti', 'flag' => 'https://bugfunx.com/flags/ht.svg'],
            ['name' => 'Honduras', 'flag' => 'https://bugfunx.com/flags/hn.svg'],
            ['name' => 'Hungary', 'flag' => 'https://bugfunx.com/flags/hu.svg'],
            ['name' => 'Iceland', 'flag' => 'https://bugfunx.com/flags/is.svg'],
            ['name' => 'India', 'flag' => 'https://bugfunx.com/flags/in.svg'],
            ['name' => 'Indonesia', 'flag' => 'https://bugfunx.com/flags/id.svg'],
            ['name' => 'Iran', 'flag' => 'https://bugfunx.com/flags/ir.svg'],
            ['name' => 'Iraq', 'flag' => 'https://bugfunx.com/flags/iq.svg'],
            ['name' => 'Ireland', 'flag' => 'https://bugfunx.com/flags/ie.svg'],
            ['name' => 'Israel', 'flag' => 'https://bugfunx.com/flags/il.svg'],
            ['name' => 'Italy', 'flag' => 'https://bugfunx.com/flags/it.svg'],
            ['name' => 'Jamaica', 'flag' => 'https://bugfunx.com/flags/jm.svg'],
            ['name' => 'Japan', 'flag' => 'https://bugfunx.com/flags/jp.svg'],
            ['name' => 'Jordan', 'flag' => 'https://bugfunx.com/flags/jo.svg'],
            ['name' => 'Kazakhstan', 'flag' => 'https://bugfunx.com/flags/kz.svg'],
            ['name' => 'Kenya', 'flag' => 'https://bugfunx.com/flags/ke.svg'],
            ['name' => 'Kiribati', 'flag' => 'https://bugfunx.com/flags/ki.svg'],
            ['name' => 'Korea, North', 'flag' => 'https://bugfunx.com/flags/kp.svg'],
            ['name' => 'Korea, South', 'flag' => 'https://bugfunx.com/flags/kr.svg'],
            ['name' => 'Kuwait', 'flag' => 'https://bugfunx.com/flags/kw.svg'],
            ['name' => 'Kyrgyzstan', 'flag' => 'https://bugfunx.com/flags/kg.svg'],
            ['name' => 'Laos', 'flag' => 'https://bugfunx.com/flags/la.svg'],
            ['name' => 'Latvia', 'flag' => 'https://bugfunx.com/flags/lv.svg'],
            ['name' => 'Lebanon', 'flag' => 'https://bugfunx.com/flags/lb.svg'],
            ['name' => 'Lesotho', 'flag' => 'https://bugfunx.com/flags/ls.svg'],
            ['name' => 'Liberia', 'flag' => 'https://bugfunx.com/flags/lr.svg'],
            ['name' => 'Libya', 'flag' => 'https://bugfunx.com/flags/ly.svg'],
            ['name' => 'Liechtenstein', 'flag' => 'https://bugfunx.com/flags/li.svg'],
            ['name' => 'Lithuania', 'flag' => 'https://bugfunx.com/flags/lt.svg'],
            ['name' => 'Luxembourg', 'flag' => 'https://bugfunx.com/flags/lu.svg'],
            ['name' => 'Madagascar', 'flag' => 'https://bugfunx.com/flags/mg.svg'],
            ['name' => 'Malawi', 'flag' => 'https://bugfunx.com/flags/mw.svg'],
            ['name' => 'Malaysia', 'flag' => 'https://bugfunx.com/flags/my.svg'],
            ['name' => 'Maldives', 'flag' => 'https://bugfunx.com/flags/mv.svg'],
            ['name' => 'Mali', 'flag' => 'https://bugfunx.com/flags/ml.svg'],
            ['name' => 'Malta', 'flag' => 'https://bugfunx.com/flags/mt.svg'],
            ['name' => 'Marshall Islands', 'flag' => 'https://bugfunx.com/flags/mh.svg'],
            ['name' => 'Mauritania', 'flag' => 'https://bugfunx.com/flags/mr.svg'],
            ['name' => 'Mauritius', 'flag' => 'https://bugfunx.com/flags/mu.svg'],
            ['name' => 'Mexico', 'flag' => 'https://bugfunx.com/flags/mx.svg'],
            ['name' => 'Micronesia', 'flag' => 'https://bugfunx.com/flags/fm.svg'],
            ['name' => 'Moldova', 'flag' => 'https://bugfunx.com/flags/md.svg'],
            ['name' => 'Monaco', 'flag' => 'https://bugfunx.com/flags/mc.svg'],
            ['name' => 'Mongolia', 'flag' => 'https://bugfunx.com/flags/mn.svg'],
            ['name' => 'Montenegro', 'flag' => 'https://bugfunx.com/flags/me.svg'],
            ['name' => 'Morocco', 'flag' => 'https://bugfunx.com/flags/ma.svg'],
            ['name' => 'Mozambique', 'flag' => 'https://bugfunx.com/flags/mz.svg'],
            ['name' => 'Myanmar', 'flag' => 'https://bugfunx.com/flags/mm.svg'],
            ['name' => 'Namibia', 'flag' => 'https://bugfunx.com/flags/na.svg'],
            ['name' => 'Nauru', 'flag' => 'https://bugfunx.com/flags/nr.svg'],
            ['name' => 'Nepal', 'flag' => 'https://bugfunx.com/flags/np.svg'],
            ['name' => 'Netherlands', 'flag' => 'https://bugfunx.com/flags/nl.svg'],
            ['name' => 'New Zealand', 'flag' => 'https://bugfunx.com/flags/nz.svg'],
            ['name' => 'Nicaragua', 'flag' => 'https://bugfunx.com/flags/ni.svg'],
            ['name' => 'Niger', 'flag' => 'https://bugfunx.com/flags/ne.svg'],
            ['name' => 'Nigeria', 'flag' => 'https://bugfunx.com/flags/ng.svg'],
            ['name' => 'North Macedonia', 'flag' => 'https://bugfunx.com/flags/mk.svg'],
            ['name' => 'Norway', 'flag' => 'https://bugfunx.com/flags/no.svg'],
            ['name' => 'Oman', 'flag' => 'https://bugfunx.com/flags/om.svg'],
            ['name' => 'Pakistan', 'flag' => 'https://bugfunx.com/flags/pk.svg'],
            ['name' => 'Palau', 'flag' => 'https://bugfunx.com/flags/pw.svg'],
            ['name' => 'Palestine', 'flag' => 'https://bugfunx.com/flags/ps.svg'],
            ['name' => 'Panama', 'flag' => 'https://bugfunx.com/flags/pa.svg'],
            ['name' => 'Papua New Guinea', 'flag' => 'https://bugfunx.com/flags/pg.svg'],
            ['name' => 'Paraguay', 'flag' => 'https://bugfunx.com/flags/py.svg'],
            ['name' => 'Peru', 'flag' => 'https://bugfunx.com/flags/pe.svg'],
            ['name' => 'Philippines', 'flag' => 'https://bugfunx.com/flags/ph.svg'],
            ['name' => 'Poland', 'flag' => 'https://bugfunx.com/flags/pl.svg'],
            ['name' => 'Portugal', 'flag' => 'https://bugfunx.com/flags/pt.svg'],
            ['name' => 'Qatar', 'flag' => 'https://bugfunx.com/flags/qa.svg'],
            ['name' => 'Romania', 'flag' => 'https://bugfunx.com/flags/ro.svg'],
            ['name' => 'Russia', 'flag' => 'https://bugfunx.com/flags/ru.svg'],
            ['name' => 'Rwanda', 'flag' => 'https://bugfunx.com/flags/rw.svg'],
            ['name' => 'Saint Kitts and Nevis', 'flag' => 'https://bugfunx.com/flags/kn.svg'],
            ['name' => 'Saint Lucia', 'flag' => 'https://bugfunx.com/flags/lc.svg'],
            ['name' => 'Saint Vincent and the Grenadines', 'flag' => 'https://bugfunx.com/flags/vc.svg'],
            ['name' => 'Samoa', 'flag' => 'https://bugfunx.com/flags/ws.svg'],
            ['name' => 'San Marino', 'flag' => 'https://bugfunx.com/flags/sm.svg'],
            ['name' => 'Sao Tome and Principe', 'flag' => 'https://bugfunx.com/flags/st.svg'],
            ['name' => 'Saudi Arabia', 'flag' => 'https://bugfunx.com/flags/sa.svg'],
            ['name' => 'Senegal', 'flag' => 'https://bugfunx.com/flags/sn.svg'],
            ['name' => 'Serbia', 'flag' => 'https://bugfunx.com/flags/rs.svg'],
            ['name' => 'Seychelles', 'flag' => 'https://bugfunx.com/flags/sc.svg'],
            ['name' => 'Sierra Leone', 'flag' => 'https://bugfunx.com/flags/sl.svg'],
            ['name' => 'Singapore', 'flag' => 'https://bugfunx.com/flags/sg.svg'],
            ['name' => 'Slovakia', 'flag' => 'https://bugfunx.com/flags/sk.svg'],
            ['name' => 'Slovenia', 'flag' => 'https://bugfunx.com/flags/si.svg'],
            ['name' => 'Solomon Islands', 'flag' => 'https://bugfunx.com/flags/sb.svg'],
            ['name' => 'Somalia', 'flag' => 'https://bugfunx.com/flags/so.svg'],
            ['name' => 'South Africa', 'flag' => 'https://bugfunx.com/flags/za.svg'],
            ['name' => 'South Sudan', 'flag' => 'https://bugfunx.com/flags/ss.svg'],
            ['name' => 'Spain', 'flag' => 'https://bugfunx.com/flags/es.svg'],
            ['name' => 'Sri Lanka', 'flag' => 'https://bugfunx.com/flags/lk.svg'],
            ['name' => 'Sudan', 'flag' => 'https://bugfunx.com/flags/sd.svg'],
            ['name' => 'Suriname', 'flag' => 'https://bugfunx.com/flags/sr.svg'],
            ['name' => 'Sweden', 'flag' => 'https://bugfunx.com/flags/se.svg'],
            ['name' => 'Switzerland', 'flag' => 'https://bugfunx.com/flags/ch.svg'],
            ['name' => 'Syria', 'flag' => 'https://bugfunx.com/flags/sy.svg'],
            ['name' => 'Taiwan', 'flag' => 'https://bugfunx.com/flags/tw.svg'],
            ['name' => 'Tajikistan', 'flag' => 'https://bugfunx.com/flags/tj.svg'],
            ['name' => 'Tanzania', 'flag' => 'https://bugfunx.com/flags/tz.svg'],
            ['name' => 'Thailand', 'flag' => 'https://bugfunx.com/flags/th.svg'],
            ['name' => 'Timor-Leste', 'flag' => 'https://bugfunx.com/flags/tl.svg'],
            ['name' => 'Togo', 'flag' => 'https://bugfunx.com/flags/tg.svg'],
            ['name' => 'Tonga', 'flag' => 'https://bugfunx.com/flags/to.svg'],
            ['name' => 'Trinidad and Tobago', 'flag' => 'https://bugfunx.com/flags/tt.svg'],
            ['name' => 'Tunisia', 'flag' => 'https://bugfunx.com/flags/tn.svg'],
            ['name' => 'Turkey', 'flag' => 'https://bugfunx.com/flags/tr.svg'],
            ['name' => 'Turkmenistan', 'flag' => 'https://bugfunx.com/flags/tm.svg'],
            ['name' => 'Tuvalu', 'flag' => 'https://bugfunx.com/flags/tv.svg'],
            ['name' => 'Uganda', 'flag' => 'https://bugfunx.com/flags/ug.svg'],
            ['name' => 'Ukraine', 'flag' => 'https://bugfunx.com/flags/ua.svg'],
            ['name' => 'United Arab Emirates', 'flag' => 'https://bugfunx.com/flags/ae.svg'],
            ['name' => 'United Kingdom', 'flag' => 'https://bugfunx.com/flags/gb.svg'],
            ['name' => 'United States', 'flag' => 'https://bugfunx.com/flags/us.svg'],
            ['name' => 'Uruguay', 'flag' => 'https://bugfunx.com/flags/uy.svg'],
            ['name' => 'Uzbekistan', 'flag' => 'https://bugfunx.com/flags/uz.svg'],
            ['name' => 'Vanuatu', 'flag' => 'https://bugfunx.com/flags/vu.svg'],
            ['name' => 'Vatican City', 'flag' => 'https://bugfunx.com/flags/va.svg'],
            ['name' => 'Venezuela', 'flag' => 'https://bugfunx.com/flags/ve.svg'],
            ['name' => 'Vietnam', 'flag' => 'https://bugfunx.com/flags/vn.svg'],
            ['name' => 'Yemen', 'flag' => 'https://bugfunx.com/flags/ye.svg'],
            ['name' => 'Zambia', 'flag' => 'https://bugfunx.com/flags/zm.svg'],
            ['name' => 'Zimbabwe', 'flag' => 'https://bugfunx.com/flags/zw.svg'],
        ];
        DB::table('territories')->insert($territories);
    }
}
